# Generated by Django 3.1 on 2020-08-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=250)),
                ('place', models.CharField(max_length=350)),
                ('rsch', models.CharField(max_length=500)),
                ('dur', models.CharField(max_length=50)),
            ],
        ),
    ]
